#MoBoxPoint By MossCG
#插件配置文件

#注意：本插件只支持Mysql环境
#yaml存数据感觉不大好使
#懒得写yaml支持（更何况这个插件就是为了大群组服务器设计的）

#Mysql配置
sqlAddress: "127.0.0.1"
sqlPort: "3389"
sqlUsername: "root"
sqlPassword: "123456"
sqlDatabase: "MoBoxMC"
sqlTable: "MoBoxPoint"

#Debug模式
#此模式开启的话会显示很多没用的信息
debug: false